[[cluster]]
name = "<ADD_YOUR_HPC_NAME_STRING>"
identify.by_environment = ["LMOD_SYSHOST", "<ADD_YOUR_HPC_NAME_STRING>"]
scheduler = "slurm"

#---- GENERAL CPU PARTITIONS FOR ADDING MULTIPLE PARTITIONS IN THE "workflow.toml" FILE ----
# Note: This does not have to be a real cluster, but should cover max and mins possible for all CPU partitions.
# Note: The top CPU partition in this file is the default one, if none is selected in the "workflow.toml" file.

[[cluster.partition]]
name = "cpu_8GB_per_cpu_add_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 0
memory_per_cpu = "8G"

[[cluster.partition]]
name = "cpu_2GB_per_cpu_add_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 0
memory_per_cpu = "2G"

[[cluster.partition]]
name = "cpu_4GB_per_cpu_add_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 0
memory_per_cpu = "4G"

[[cluster.partition]]
name = "cpu_16GB_per_cpu_add_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 0
memory_per_cpu = "16G"

[[cluster.partition]]
name = "cpu_32GB_per_cpu_add_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 0
memory_per_cpu = "32G"

[[cluster.partition]]
name = "cpu_64GB_per_cpu_add_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 0
memory_per_cpu = "64G"

[[cluster.partition]]
name = "cpu_128GB_per_cpu_add_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 0
memory_per_cpu = "128G"

[[cluster.partition]]
name = "cpu_256GB_per_cpu_add_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 0
memory_per_cpu = "256G"

[[cluster.partition]]
name = "cpu_512GB_per_cpu_add_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 0
memory_per_cpu = "512G"

[[cluster.partition]]
name = "cpu_1000GB_per_cpu_add_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 0
memory_per_cpu = "1000G"

#---- GENERAL GPU PARTITIONS FOR ADDING MULTIPLE PARTITIONS IN THE "workflow.toml" FILE ----
# Note: This does not have to be a real cluster, but should cover max and mins possible for all GPU partitions.
# Note: The top GPU partition in this file is the default one, if none is selected in the "workflow.toml" file.

[[cluster.partition]]
name = "gpu_add_8GB_per_gpu_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 8
minimum_gpus_per_job = 1
memory_per_gpu = "8G"

[[cluster.partition]]
name = "gpu_add_2GB_per_gpu_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 8
minimum_gpus_per_job = 1
memory_per_gpu = "2G"

[[cluster.partition]]
name = "gpu_add_4GB_per_gpu_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 8
minimum_gpus_per_job = 1
memory_per_gpu = "4G"

[[cluster.partition]]
name = "gpu_add_16GB_per_gpu_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 8
minimum_gpus_per_job = 1
memory_per_gpu = "16G"

[[cluster.partition]]
name = "gpu_add_32GB_per_gpu_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 8
minimum_gpus_per_job = 1
memory_per_gpu = "32G"

[[cluster.partition]]
name = "gpu_add_64GB_per_GPU_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 8
minimum_gpus_per_job = 1
memory_per_gpu = "64G"

[[cluster.partition]]
name = "gpu_add_128GB_per_gpu_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 8
minimum_gpus_per_job = 1
memory_per_gpu = "128G"

[[cluster.partition]]
name = "gpu_add_256GB_per_GPU_1+_partitions_in_custom_only"
maximum_cpus_per_job = 112
maximum_gpus_per_job = 8
minimum_gpus_per_job = 1
memory_per_gpu = "256G"

[[cluster.partition]]
name = "gpu_add_512GB_per_gpu_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 8
minimum_gpus_per_job = 1
memory_per_gpu = "512G"

[[cluster.partition]]
name = "gpu_add_1000GB_per_gpu_1+_partitions_in_custom_only"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 8
minimum_gpus_per_job = 1
memory_per_gpu = "1000G"