[[cluster]]
name = "<ADD_YOUR_HPC_NAME_STRING>"
identify.by_environment = ["LMOD_SYSHOST", "<ADD_YOUR_HPC_NAME_STRING>"]
scheduler = "slurm"

#---- GENERAL CPU PARTITIONS FOR ADDING MULTIPLE PARTITIONS IN THE "workflow.toml" FILE ----
# Note: This does not have to be a real cluster, but should cover max and mins possible for all CPU partitions.
# Note: The top CPU partition in this file is the default one, if none is selected in the "workflow.toml" file.
# Note: The memory per CPU can be changed in the 'workflow.toml' file.

[[cluster.partition]]
name = "cpu_general_not_real_partition"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 0
minimum_gpus_per_job = 0


#---- GENERAL GPU PARTITIONS FOR ADDING MULTIPLE PARTITIONS IN THE "workflow.toml" FILE ----
# Note: This does not have to be a real cluster, but should cover max and mins possible for all GPU partitions.
# Note: The top GPU partition in this file is the default one, if none is selected in the "workflow.toml" file.
# Note: The memory per GPU can be changed in the 'workflow.toml' file.

[[cluster.partition]]
name = "gpu_general_not_real_partition"
maximum_cpus_per_job = 128
maximum_gpus_per_job = 8
minimum_gpus_per_job = 1