#---------------------
[workspace]
value_file = "signac_statepoint.json"

#---------------------
[default.action]
command = "python actions.py --action $ACTION_NAME {directories}"

#---------------------
[[action]]
name = "part_1_initial_parameters_command"
products = ["signac_job_document.json"]

[action.group]
maximum_size = 1

[action.resources]
processes.per_directory = 1
threads_per_process = 1
memory_per_cpu_mb = 7_100
walltime.per_submission = "00:11:00"

# ****** USED ONLY FOR SLURM SUBMISSION - REMOVE OR '#' OUT IF RUNNING LOCALLY (START) ******

[action.submit_options.<ADD_YOUR_HPC_NAME>]
account = <ADD_YOUR_CHARGE_ACCOUNT_NAME_STRING>
setup = """
module load mamba
mamba activate signac_numpy_tutorial
"""

# You can also select a real partition if it is in the 'clusters.toml' file, 
# and then you do not need to add the '--partition' info in 'custom'.
# However, this will only select a single partition.  If you want more 
# If you do not want the slurm 'output' and 'error' files written, 
# you can add "--output=/dev/null" and "--error=/dev/null" in the 'custom list.
partition = "cpu_general_not_real_partition"
custom = ["", "--partition=cpu-1,cpu-1,cpu-3"]

# ****** USED ONLY FOR SLURM SUBMISSION - REMOVE OR '#' OUT IF RUNNING LOCALLY (END) ******

#---------------------
[[action]]
name = "part_2_write_numpy_input_command"
products = ["numpy_input_file.txt"]
previous_actions = ["part_1_initial_parameters_command"]

[action.group]
maximum_size = 1

[action.resources]
processes.per_directory = 1
threads_per_process = 1
memory_per_cpu_mb = 7_200
walltime.per_submission = "00:12:00"

# ****** USED ONLY FOR SLURM SUBMISSION - REMOVE OR '#' OUT IF RUNNING LOCALLY (START) ******

[action.submit_options.<ADD_YOUR_HPC_NAME>]
account = <ADD_YOUR_CHARGE_ACCOUNT_NAME_STRING>
setup = """
module load mamba
mamba activate signac_numpy_tutorial
"""

# You can also select a real partition if it is in the 'clusters.toml' file, 
# and then you do not need to add the '--partition' info in 'custom'.
# However, this will only select a single partition.  If you want more 
# than 1 partition, you should do it the same way as below.
# If you do not want the slurm 'output' and 'error' files written, 
# you can add "--output=/dev/null" and "--error=/dev/null" in the 'custom list.
partition = "cpu_general_not_real_partition"
custom = ["", "--partition=cpu-1,cpu-1,cpu-3"]

# ****** USED ONLY FOR SLURM SUBMISSION - REMOVE OR '#' OUT IF RUNNING LOCALLY (END) ******

#---------------------
[[action]]
name = "part_3_numpy_calcs_command"
products = ["numpy_output_file.txt"]
previous_actions = ["part_2_write_numpy_input_command"]

[action.group]
maximum_size = 1

[action.resources]
processes.per_directory = 1
# Change the GPU parts to run only on CPU, if the local hardware 
# is supports CPU workflows (see the notes in the workflow.toml).
# This means remove the'gpus_per_process' and change the 'partition', 
# and 'custom' variables below.
gpus_per_process = 1
threads_per_process = 1
memory_per_cpu_mb = 7_300
walltime.per_submission = "00:13:00"

# ****** USED ONLY FOR SLURM SUBMISSION - REMOVE OR '#' OUT IF RUNNING LOCALLY (START) ******

[action.submit_options.<ADD_YOUR_HPC_NAME>]
account = <ADD_YOUR_CHARGE_ACCOUNT_NAME_STRING>
setup = """
module reset
module load cuda
module load mamba
mamba activate signac_numpy_tutorial
"""

# You can also select a real partition if it is in the 'clusters.toml' file, 
# and then you do not need to add the '--partition' info in 'custom'.
# However, this will only select a single partition.  If you want more 
# than 1 partition, you should do it the same way as below.
# If you do not want the slurm 'output' and 'error' files written, 
# you can add "--output=/dev/null" and "--error=/dev/null" in the 'custom list.
partition = "gpu_general_not_real_partition"
custom = ["", "--partition=gpu-1,gpu-1,gpu-3"]

# ****** USED ONLY FOR SLURM SUBMISSION - REMOVE OR '#' OUT IF RUNNING LOCALLY (END) ******

#---------------------
[[action]]
name = "part_4_analysis_replicate_averages_command"
products = ["avg_std_dev_calculated.txt"]
previous_actions = ["part_3_numpy_calcs_command"]

[action.group]
submit_whole = true
sort_by = ["/value_0_int"]
split_by_sort_key = true

[action.resources]
processes.per_submission = 1
threads_per_process = 1
memory_per_cpu_mb = 7_400
walltime.per_submission = "00:14:00"

# ****** USED ONLY FOR SLURM SUBMISSION - REMOVE OR '#' OUT IF RUNNING LOCALLY (START) ******

[action.submit_options.<ADD_YOUR_HPC_NAME>]
account = <ADD_YOUR_CHARGE_ACCOUNT_NAME_STRING>
setup = """
module load mamba
mamba activate signac_numpy_tutorial
"""

# You can also select a real partition if it is in the 'clusters.toml' file, 
# and then you do not need to add the '--partition' info in 'custom'.
# However, this will only select a single partition.  If you want more 
# than 1 partition, you should do it the same way as below.
# If you do not want the slurm 'output' and 'error' files written, 
# you can add "--output=/dev/null" and "--error=/dev/null" in the 'custom list.
partition = "cpu_general_not_real_partition"
custom = ["", "--partition=cpu-1,cpu-1,cpu-3"]

# ****** USED ONLY FOR SLURM SUBMISSION - REMOVE OR '#' OUT IF RUNNING LOCALLY (END) ******
