#---------------------
[workspace]
value_file = "signac_statepoint.json"

#---------------------
[default.action]
command = "python actions.py --action $ACTION_NAME {directories}"

#---------------------
[[action]]
name = "part_1_initial_parameters_command"
products = ["signac_job_document.json"]

[action.group]
maximum_size = 1

[action.resources]
processes.per_directory = 1
gpus_per_process = 0
threads_per_process = 1
walltime.per_submission = "00:10:00"

[action.submit_options.<ADD_YOUR_HPC_NAME>]
account = "<ADD_YOUR_CHARGE_ACCOUNT_NAME>"
setup = """
module load mamba
mamba activate signac_numpy_tutorial
"""
custom = ["","--partition='cpu-1, cpu-1, cpu-3'"]
partition = "cpu_8GB_per_cpu_add_1+_partitions_in_custom_only"

#---------------------
[[action]]
name = "part_2_write_numpy_input_command"
products = ["numpy_input_file.txt"]
previous_actions = ["part_1_initial_parameters_command"]

[action.group]
maximum_size = 1

[action.resources]
processes.per_directory = 1
gpus_per_process = 0
threads_per_process = 1
walltime.per_submission = "00:11:00"

[action.submit_options.<ADD_YOUR_HPC_NAME>]
account = "<ADD_YOUR_CHARGE_ACCOUNT_NAME>"
setup = """
module load mamba
mamba activate signac_numpy_tutorial
"""
custom = ["","--partition='cpu-1, cpu-1, cpu-3'"]
partition = "cpu_8GB_per_cpu_add_1+_partitions_in_custom_only"

#---------------------
[[action]]
name = "part_3_numpy_calcs_command"
products = ["numpy_output_file.txt"]
previous_actions = ["part_2_write_numpy_input_command"]

[action.group]
maximum_size = 1

[action.resources]
processes.per_directory = 1
gpus_per_process = 1
threads_per_process = 1
walltime.per_submission = "00:12:00"

[action.submit_options.<ADD_YOUR_HPC_NAME>]
account = "<ADD_YOUR_CHARGE_ACCOUNT_NAME>"
setup = """
module reset
module load cuda
module load mamba
mamba activate signac_numpy_tutorial
"""
custom = ["","--partition='cpu-1, cpu-1, cpu-3'"]
partition = "gpu_8GB_per_gpu_add_1+_partitions_in_custom_only"

#---------------------
[[action]]
name = "part_4_analysis_replicate_averages_command"
products = ["avg_std_dev_calculated.txt"]
previous_actions = ["part_3_numpy_calcs_command"]

[action.group]
submit_whole = true
sort_by = ["/value_0_int"]
split_by_sort_key = true

[action.resources]
processes.per_directory = 1
gpus_per_process = 0
threads_per_process = 1
walltime.per_submission = "00:13:00"

[action.submit_options.<ADD_YOUR_HPC_NAME>]
account = "<ADD_YOUR_CHARGE_ACCOUNT_NAME>"
setup = """
module load mamba
mamba activate signac_numpy_tutorial
"""
custom = ["","--partition='cpu-1, cpu-1, cpu-3'"]
partition = "cpu_8GB_per_cpu_add_1+_partitions_in_custom_only"
